/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.Chat;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
/**
 *
 * @author MINH THUY
 */
public class messageListCLI  extends javax.swing.JPanel implements ListCellRenderer<messageData>{
    private final String user = "CLI" ;
    /**
     * Creates new form messageList
     * @param user
     */
    public messageListCLI(String user) {
        initComponents();
        this.user.replaceAll(this.user, user);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        messageBg = new javax.swing.JPanel();
        textContent = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 153, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        messageBg.setBackground(new java.awt.Color(51, 153, 255));

        textContent.setBackground(new java.awt.Color(255, 255, 255));
        textContent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textContent.setForeground(new java.awt.Color(255, 255, 255));
        textContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textContent.setText("Tin nhắn mẫu");

        avatar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 14)); // NOI18N
        avatar.setForeground(new java.awt.Color(255, 255, 255));
        avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar.setText("CLI");

        javax.swing.GroupLayout messageBgLayout = new javax.swing.GroupLayout(messageBg);
        messageBg.setLayout(messageBgLayout);
        messageBgLayout.setHorizontalGroup(
            messageBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageBgLayout.createSequentialGroup()
                .addComponent(textContent, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avatar, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
        );
        messageBgLayout.setVerticalGroup(
            messageBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avatar, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messageBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(messageBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel messageBg;
    private javax.swing.JLabel textContent;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public Component getListCellRendererComponent(JList<? extends messageData> list,  messageData msgData, int index, boolean isSelected, boolean cellHasFocus) {
        if(!msgData.getUser().equals(this.user))
       {
          this.messageBg.setBackground(new java.awt.Color(255, 255, 255));
            this.avatar.setForeground(new java.awt.Color(0,0,0));
            this.textContent.setForeground(new java.awt.Color(0,0,0)); 
          
       }
       else
       {
         
            this.messageBg.setBackground(new java.awt.Color(51, 153, 255));
           this.avatar.setForeground(new java.awt.Color(255,255,255));
            this.textContent.setForeground(new java.awt.Color(255,255,255)); 
       }
           this.avatar.setText(msgData.getUser());
           this.textContent.setText(msgData.getTextContent());
           
        return this;
    }
}
